# Introduction to NumPy
* NumPy (Numerical Python) is a fundamental library for numerical operations in Python. It provides efficient support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays.
## Benefits of using NumPy over standard Python lists:
* NumPy arrays are more compact in memory and faster in execution.
* NumPy provides a wide range of mathematical functions and operations optimized for scientific computing.
* NumPy arrays can be easily integrated with other scientific computing libraries like SciPy and Matplotlib.

# Installing NumPy
* You can install NumPy using the Python package installer pip:

In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 14.0 MB 145 kB/s eta 0:00:01    |█▋                              | 716 kB 147 kB/s eta 0:01:31
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


* To verify the installation and check the NumPy version, you can use:

In [2]:
import numpy as np
print(np.__version__)

1.26.4


# NumPy Arrays
* NumPy arrays are the core data structure in NumPy. They are similar to Python lists but more efficient and optimized for numerical operations.

* Some commonly used numpy Attributes: 
1. shape: The shape attribute returns a tuple representing the dimensions of the array.

In [5]:
# 1D array
a = np.array([1, 2, 3, 4, 5])
print(a.shape)  

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)  

# 3D array
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c.shape)  

(5,)
(2, 3)
(2, 2, 2)


2. size: The size attribute returns the total number of elements in the array.

In [6]:
a = np.array([1, 2, 3, 4, 5])
print(a.size) 

5


3. dtype: The dtype attribute represents the data type of the array elements.

In [7]:
# Integer array
a = np.array([1, 2, 3, 4, 5])
print(a.dtype) 

# Float array
b = np.array([1.0, 2.0, 3.0])
print(b.dtype)  

# Complex array
c = np.array([1+2j, 3+4j])
print(c.dtype)  

# Boolean array
d = np.array([True, False, True])
print(d.dtype)  

int64
float64
complex128
bool


* You can also specify the data type when creating an array using the dtype parameter:

In [26]:
# Create an array with float32 data type
a = np.array([1, 2, 3], dtype=np.float32)
print(a)        
print(a.dtype)  

[1. 2. 3.]
float32


In [27]:
# Create an array with int16 data type
b = np.array([1, 2, 3], dtype=np.int16)
print(b)        
print(b.dtype)  

[1 2 3]
int16


* Some commonly used functions to create arrays:
1. np.array(): Create an array from a Python list or sequence.

In [25]:
# From a list
a = np.array([1, 2, 3, 4, 5])
print(a)  

[1 2 3 4 5]


In [24]:
# From a sequence
b = np.array((10, 20, 30))
print(b)  

[10 20 30]


2. np.asarray(): Convert the input to an array.

In [4]:
# From a list
c = [1, 2, 3, 4, 5]
a = np.asarray(c)
print(a)  

[1 2 3 4 5]
[10 20 30]


In [23]:
# From a tuple
d = (10, 20, 30)
b = np.asarray(d)
print(b)  

[10 20 30]


3. np.ones(): Create an array filled with ones.

In [28]:
# Create a 1D array of ones
a = np.ones(5)
print(a)  

[1. 1. 1. 1. 1.]


In [29]:
# Create a 2D array of ones with shape (3, 4)
b = np.ones((3, 4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4. np.zeros(): Create an array filled with zeros.

In [30]:
# Create a 1D array of zeros
a = np.zeros(5)
print(a)  

[0. 0. 0. 0. 0.]


In [31]:
# Create a 2D array of zeros with shape (2, 3)
b = np.zeros((2, 3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


5. np.empty(): Create an uninitialized array.

In [32]:
# Create an uninitialized 1D array
a = np.empty(5)
print(a)

[0. 0. 0. 0. 0.]


In [33]:
# Create an uninitialized 2D array with shape (2, 3)
b = np.empty((2, 3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


6. np.arange(): Create a sequence of numbers within a range.

In [34]:
# Create a sequence from 0 to 9
a = np.arange(10)
print(a)  

[0 1 2 3 4 5 6 7 8 9]


In [35]:
# Create a sequence from 2 to 10 with step size 2
b = np.arange(2, 11, 2)
print(b)  

[ 2  4  6  8 10]


7. np.linspace(): Create an array with evenly spaced values within a range.

In [18]:
# Create an array with 5 evenly spaced values between 0 and 1
a = np.linspace(0, 1, 5)
print(a) 


[0.   0.25 0.5  0.75 1.  ]


In [17]:
# Create an array with 9 evenly spaced values between 0 and 10
b = np.linspace(0, 10, 9)
print(b)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


8. np.eye(): Create a square identity matrix.

In [16]:
# Create a 2x2 identity matrix
a = np.eye(2)
print(a)


[[1. 0.]
 [0. 1.]]


In [15]:
# Create a 3x3 identity matrix
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Numpy Array Operations and Broadcasting

**1. Basic Array Operations**

- Addition: Adds two arrays element-wise.

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

[5 7 9]


- Subtraction: Subtracts two arrays element-wise.

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = b - a
print(c) 

[3 3 3]


- Multiplication: Multiplies two arrays element-wise.

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a * b
print(c)  

[ 4 10 18]


- Division: Divides two arrays element-wise.

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = b / a
print(c)  

[4.  2.5 2. ]


- Scalar Operations: Multiplies/Divides each element of the array by the scalar value; 


In [6]:
a = np.array([1, 2, 3])

b = a * 2
print(b)  

c = a / 2
print(c) 

[2 4 6]
[0.5 1.  1.5]


- Square Root(np.sqrt()): Computes the square root of each element in the array.

In [7]:
a = np.array([1, 4, 9])

b = np.sqrt(a)
print(b) 

[1. 2. 3.]


- Exponential(np.exp()): Computes the exponential of each element in the array.

In [8]:
a = np.array([1, 2, 3])

b = np.exp(a)
print(b) 

[ 2.71828183  7.3890561  20.08553692]


**2. Broadcasting**

- Broadcasting is a powerful mechanism in NumPy that allows arithmetic operations between arrays with different shapes. 
- It automatically duplicates the smaller array along the missing dimensions to match the shape of the larger array. 
- This makes it possible to perform operations on arrays with different shapes without explicitly reshaping them.

1D Array and Scalar

In [11]:
# 1D array and scalar
a = np.array([1, 2, 3])
b = 2
c = a + b  
print(c)

[3 4 5]


2D Array and 1D Array

In [12]:
# 2D array and 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
c = a + b
print(c)

[[11 22 33]
 [14 25 36]]


Broadcasting follows certain rules:

- If the arrays have the same shape, no broadcasting is necessary, and the operation is performed element-wise.
- If the arrays have different shapes, NumPy attempts to broadcast the smaller array's shape to match the larger array's shape.
- If the dimensions of the arrays are different, NumPy starts from the trailing dimensions and works backward, prepending 1s to the smaller shape until the shapes match.
- If the shapes still don't match after prepending 1s, NumPy raises a ValueError.

- Example Of Where Broadcasting is not possible

In [13]:
# Different shapes: (2, 3) and (3, 2)
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2], [3, 4], [5, 6]])
c = a + b  

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

**3. Element-wise Operations And Their Efficiency**

- In NumPy, element-wise operations are performed on arrays in a highly efficient manner. 
- This efficiency comes from the fact that NumPy is written in a combination of Python and optimized C code, allowing it to leverage the computational power of low-level languages like C for numerical operations.
- Element-wise operations in NumPy are vectorized, meaning that they are applied to entire arrays at once, rather than iterating over individual elements. - This vectorization is a key factor in NumPy's efficiency, as it avoids the overhead of Python-level loops and allows the operations to be performed in a single step.

- Here's an example of how element-wise operations are efficient in NumPy:

In [14]:
import time

# Create large arrays
a = np.random.rand(10000000)
b = np.random.rand(10000000)

# Element-wise operations in NumPy
start = time.time()
c = a + b
end = time.time()
print(f"NumPy element-wise addition took: {end - start:.6f} seconds")

# Element-wise operations in Python lists
start = time.time()
x = [i for i in range(10000000)]
y = [i for i in range(10000000)]
z = [x[i] + y[i] for i in range(10000000)]
end = time.time()
print(f"Python list element-wise addition took: {end - start:.6f} seconds")

NumPy element-wise addition took: 0.086844 seconds
Python list element-wise addition took: 12.424693 seconds


As you can see, the element-wise addition operation in NumPy is significantly faster than the equivalent operation on Python lists, even for large arrays or lists with millions of elements.

This efficiency is achieved through several factors:

- Vectorization: NumPy can perform operations on entire arrays in a single step, avoiding the overhead of Python-level loops.
- Optimized C code: NumPy's core operations are written in optimized C code, which is much faster than pure Python code.
- Contiguous memory layout: NumPy arrays are stored in a contiguous block of memory, which allows for efficient memory access and cache optimization.
- Parallelization: Some NumPy operations can take advantage of multi-core processors and parallel computing, further improving performance.

# Indexing and Slicing

#### **1. Indexing**

- Indexing in NumPy arrays is a way to access individual elements or subsets of the array data. 
- NumPy provides various indexing techniques that allow you to work with arrays in a flexible and efficient manner.

**a) Basic Indexing**

- You can access individual elements using their position indices, similar to Python lists.
- For 1D arrays, you provide a single index.
- For multidimensional arrays, you provide a tuple of indices, one for each dimension.

In [15]:
# 1D array
a = np.array([1, 2, 3, 4, 5])
print(a[0])  
print(a[3])  


1
4


In [16]:
# 2D array
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[0, 0])  
print(b[2, 1])  

1
8


**b) Fancy Indexing**

- Fancy indexing allows you to select elements or subarrays using arrays of integers or boolean arrays.
- This is useful when you need to select arbitrary elements or subarrays based on specific conditions or indices.

In [17]:
# 1D array
a = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 4])
print(a[indices])

[1 3 5]


In [18]:
# 2D array
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = np.array([0, 2])
cols = np.array([0, 2])
print(b[rows, cols])

[1 9]


**c) Boolean Indexing**

- Boolean indexing is a powerful way to select elements or subarrays based on a condition or boolean array.
- It allows you to filter the array based on specific criteria.

In [19]:
a = np.array([1, 2, 3, 4, 5])
print(a[a > 3])

[4 5]


In [20]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[b > 5]) 

[6 7 8 9]


#### **2. Slicing**

- Slicing in NumPy arrays is a powerful technique that allows you to extract a subset or a view of an array based on specified indices or ranges. 
- NumPy's slicing is similar to Python's list slicing but extends to multidimensional arrays.

**a) One-Dimensional Array Slicing**
- You can slice a 1D array using the start:stop:step notation, just like in Python lists.
- The start index is inclusive, and the stop index is exclusive.

In [21]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[2:6])  
print(a[:4])   
print(a[5:])   
print(a[::2])
print(a[::-1]) 

[3 4 5 6]
[1 2 3 4]
[6 7 8 9]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]


**b) Multidimensional Array Slicing**
- For multidimensional arrays, you can specify a slice for each dimension, separated by commas.
- If you omit a dimension in the slicing, it selects all elements along that dimension.

In [22]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[0:2, 0:2])  
print(b[:, 1])      
print(b[1:, :2])    

[[1 2]
 [4 5]]
[2 5 8]
[[4 5]
 [7 8]]


**c) Slicing with Step size**
- You can also specify a step size for slicing by providing a third value in the start:stop:step notation.
- Negative step sizes are allowed, which reverses the order of the elements.

In [23]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[::3])  
print(a[::-2]) 

[1 4 7]
[9 7 5 3 1]


**d) Assigning Values To Slices**
- You can assign values to a slice of an array, which modifies the original array.
- The assigned value should have a compatible shape with the slice.

In [3]:
a = np.array([1, 2, 3, 4, 5])
a[1:4] = 10
print(a)

[ 1 10 10 10  5]


# Array Manipulation

#### 1. **Reshaping Arrays**
- Reshaping is the process of changing the shape (dimensions) of an array without modifying its data. 
- This is useful when you need to work with the same data in a different dimensional representation.

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)  

# Reshape to a 2D array
b = a.reshape(2, 3)
print(b)

# Reshape to a 3D array
c = a.reshape(2, 1, 3)
print(c)

(6,)
[[1 2 3]
 [4 5 6]]
[[[1 2 3]]

 [[4 5 6]]]


#### **2. Flattening Arrays**
- Flattening is the process of converting a multidimensional array into a one-dimensional (1D) array. 
- This can be useful when you need to operate on all elements of the array as a single sequence.

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)  

# Flatten the array
b = a.ravel()
print(b)  

(2, 3)
[1 2 3 4 5 6]


#### **3. Concatenating Arrays**
- Concatenation is the process of joining two or more arrays together, either along a new axis (stacking) or along an existing axis.

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenate along a new axis (stacking)
c = np.stack((a, b))
print(c)

# Concatenate along an existing axis (horizontal)
d = np.concatenate((a, b), axis=None)
print(d)  

# Concatenate along an existing axis (vertical)
e = np.array([[1, 2], [3, 4]])
f = np.array([[5, 6], [7, 8]])
g = np.concatenate((e, f), axis=0)
print(g)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Stacking and Splitting of Arrays
In NumPy, stacking and splitting are operations that allow you to combine or divide arrays along different axes. These operations are particularly useful when working with multidimensional arrays and can help you organize and manipulate data more effectively.

#### **1. Stacking Arrays**
Stacking is the process of combining arrays along a new axis. NumPy provides several functions for stacking arrays:

- np.stack(arrays, axis=0): <br>
This function stacks the arrays along a new axis. The axis parameter specifies the axis along which the arrays are stacked.
- np.vstack(arrays): <br>
This function stacks the arrays vertically (row-wise) by combining them along the first axis (axis=0).
- np.hstack(arrays): <br>
This function stacks the arrays horizontally (column-wise) by combining them along the second axis (axis=1).

In [7]:
a = np.array([1, 2])
b = np.array([3, 4])

# Stack arrays horizontally
c = np.hstack((a, b))
print(c)

# Stack arrays vertically
d = np.vstack((a, b))
print(d)

# Stack arrays along a new axis
e = np.stack((a, b), axis=1)
print(e)

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


#### **2. Splitting Arrays**
Splitting is the opposite operation of stacking, where an array is divided into multiple sub-arrays along a specified axis. <br>
<br>
NumPy provides several functions for splitting arrays:


- np.split(array, indices_or_sections, axis=0): <br>
This function splits the array into multiple sub-arrays along the specified axis. You can either provide the indices where the array should be split or the number of equal sections to split the array into.
- np.vsplit(array, indices_or_sections): <br>
This function splits the array vertically (row-wise) by dividing it along the first axis (axis=0).
- np.hsplit(array, indices_or_sections): <br>
This function splits the array horizontally (column-wise) by dividing it along the second axis (axis=1).

In [12]:
# Create a 2D array
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Split the array horizontally into 2 sub-arrays
left, right = np.hsplit(a, 2)
print("Horizontal split:")
print("Left sub-array:\n", left)
print("Right sub-array:\n", right)


Horizontal split:
Left sub-array:
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
Right sub-array:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


# Methods for Adding and Removing elements
NumPy provides several methods for adding and removing elements from arrays. These operations are particularly useful when you need to modify the size or shape of an array dynamically. <br>
Here are some common methods for adding and removing elements:

#### **1. Appending Elements**
##### np.append(arr, values, axis=None):
- This method appends the values to the end of the arr array. <br>
- The axis parameter specifies the axis along which the values are appended. <br>
- If axis is not provided, it flattens the input array and appends the values as a flat sequence.





In [13]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5])
print(b)  

c = np.array([[1, 2], [3, 4]])
d = np.append(c, [[5, 6]], axis=0)
print(d)

[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]


#### **2. Inserting Elements**
##### np.insert(arr, obj, values, axis=None):
- This method inserts the values into the arr array before the elements at the specified obj indices. 
- The axis parameter specifies the axis along which the values are inserted.

In [14]:
a = np.array([1, 2, 3, 4, 5])
b = np.insert(a, 2, [10, 20])
print(b) 

c = np.array([[1, 2], [3, 4]])
d = np.insert(c, 1, [10, 20], axis=1)
print(d)

[ 1  2 10 20  3  4  5]
[[ 1 10  2]
 [ 3 20  4]]


#### **3. Deleting Elements**
##### np.delete(arr, obj, axis=None): 
- This method removes the elements from the arr array at the specified obj indices. 
- The axis parameter specifies the axis along which the elements are removed.

In [15]:
a = np.array([1, 2, 3, 4, 5])
b = np.delete(a, [0, 2])
print(b) 

c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.delete(c, 1, axis=1)
print(d)

[2 4 5]
[[1 3]
 [4 6]]


#### **4. Resizing Arrays** 
##### np.resize(arr, new_shape): 
- This method resizes the arr array to the specified new_shape. 
- If the new shape is larger than the original array, new elements are filled with zeros.

In [16]:
a = np.array([1, 2, 3, 4, 5])
b = np.resize(a, (3, 3))
print(b)

[[1 2 3]
 [4 5 1]
 [2 3 4]]


# Hands-On Exercises

#### **Array Operations and Broadcasting:**

1. Given a 3D array a with shape (2, 3, 4) and a 2D array b with shape (3, 4), perform element-wise multiplication between a and b using broadcasting.
2. Implement a function that takes two 2D arrays c and d with different shapes and performs element-wise operations (addition, subtraction, multiplication, and division) between them using broadcasting. Handle the case where broadcasting is not possible.
3. Create a 2D array e with shape (5, 3) and a 1D array f with length 5. Compute the outer product of e and f using broadcasting.


#### **Indexing and Slicing:**

1. Given a 3D array g with shape (4, 3, 2), extract every other element along the first and second dimensions, but keep all elements along the third dimension.
2. Create a function that takes a 2D array h and an array of row indices i and column indices j. The function should return a new array k where k[m, n] is the sum of the elements in h along the diagonal specified by i[m] and j[n].
3. Implement a function that takes a 2D array l and returns a new array m where each element in m is the product of the corresponding row and column means in l.


#### **Array Manipulation:**

1. Given a 2D array n with shape (4, 6), reshape it into a 3D array with shape (2, 2, 6) and then flatten it back to a 2D array with shape (4, 6).
2. Implement a function that takes a 2D array o and rolls it along the first axis by a specified number of positions. For example, if the input array is [[1, 2, 3], [4, 5, 6]] and the number of positions is 1, the output should be [[4, 5, 6], [1, 2, 3]].
3. Create a function that takes a 2D array p and replaces all occurrences of a specified value x with the mean of the neighboring elements (horizontally and vertically) in the array.